### ISSUE TITLE
Error Create Table

### ISSUE THREAD

**Issue by ghost** [valarauco/roundcube-plugin-admin-notifications#1] opened 2018-02-20 08:58 UTC
SQL query:

CREATE TABLE IF NOT EXISTS `adminnotifications` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) UNSIGNED NOT NULL,
  `mod_user_id` int(10) UNSIGNED NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` varchar(100) NOT NULL,
  `message` longtext NOT NULL,
  `html` tinyint(1) NOT NULL DEFAULT 0,  
  `type` int(10) NOT NULL DEFAULT 0,
  `active` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id_fk_adminnotifications` FOREIGN KEY (`user_id`)
   REFERENCES `users`(`user_id`),
  CONSTRAINT `mod_user_id_fk_adminnotifications` FOREIGN KEY (`mod_user_id`)
   REFERENCES `users`(`user_id`),
  INDEX `user_adminnotifications_index` (`id`, `active`)
)
MySQL said: Documentation

#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

**Comment by valarauco** [comment] 2018-02-20 16:57
Oh, my bad... I'm actually using MariaDB and it seems it doesn't have this limitation. 
My error was to assume it would work the same in MySQL and MariaDB.

**Comment by valarauco** [comment] 2018-02-22 22:05
Hi @bogdanpuica 
I found this:
https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-5.html

> Previously, at most one TIMESTAMP column per table could be automatically initialized or updated to the current date and time. This restriction has been lifted. Any TIMESTAMP column definition can have any combination of DEFAULT CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP clauses. In addition, these clauses now can be used with DATETIME column definitions. For more information, see Automatic Initialization and Updating for TIMESTAMP and DATETIME. 

Can you check if MySQL version is lower than 5.6.5

**Comment by madeus** [comment] 2018-02-26 09:07
@valarauco 

I have exactly the same error message. I use MariaDB 5.5.56.

**Comment by valarauco** [comment] 2018-02-26 18:16
Hi @madeus 

MariaDB 5.5 is "MariaDB 5.3 MySQL 5.5" and its support ends in 2020... I recommend you migrate to MariaDB 10.
Nevertheless I will try to reproduce the error (both MySQL 5.6 and MariaDB 5.5).

**Comment by madeus** [comment] 2018-02-27 20:05
@valarauco 

I know but I still have two years. ;-) Anyway, thanks for your interest.

**Comment by valarauco** [comment] 2018-03-12 21:37
I can confirm the issue in MariaDB 5.5.59 but it works in MySQL 5.6.

Googling around I found a workaround (one I don't like): change default value to 0 on "created" column.

> `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',

If someone has a better fix for this it will be appreciated... I will do some more test but in the mean time @madeus you can fix it changing the SQL as shown above.

I'm not sure if I can make a "special version" for old-mysql in plugins.roundcube.net

**Comment by madeus** [comment] 2018-03-13 19:54
@valarauco 

First thank you for your time. It works. ;-) But, when I create new notifications, nothing happens. Maybe you could expand the Readme sections? ;-)

**Comment by valarauco** [comment] 2018-03-13 22:28
Maybe because of this: https://github.com/valarauco/roundcube-plugin-admin-notifications/commit/ea3130135bf18994767f85041bf7f5aaf505a5a9

> Maybe you could expand the Readme sections
Yes, I have work to do in the README and fix some tab/space issues that make my code ugly hahaha.

I will be pushing the changes soon and close this issue.

**Closed as completed** 2018-03-14 22:52 UTC
